modLoader="javafml" #mandatory
loaderVersion="[37,)" 
license="MIT"
# A list of mods - how many allowed here is determined by the individual mod loader
[[mods]] 
modId="arcade" 
version="1.0" 
displayName="Arcade!!" 
logoFile="examplemod.png" 
credits="TheOnlineWizards" #optional
authors="TheOnlineWizards" #optional
description='''


'''

